import type { TumbleweedJson } from '../types.ts';

/**
 * 把 Tumbleweed.json 嵌入 bash here-doc，再附带 deploy.sh 主体逻辑。
 * 用户解压 zip 后只需 `bash deploy.sh` 即可。
 */
function renderBash(json: TumbleweedJson): string {
  const jsonText = JSON.stringify(json, null, 2);
  return `#!/usr/bin/env bash
# Tumbleweed deploy.sh — generated by tumbleweed-mc ${json.tumbleweed?.packerVersion ?? '0.1.0'}
# 用法：bash deploy.sh [工作目录]
set -euo pipefail

echo "Generated by Tumbleweed ${json.tumbleweed?.packerVersion ?? '0.1.0'}"

WORK="\${1:-.}"
cd "$WORK"

# 内嵌 Tumbleweed.json（here-doc）
TUMBLEWEED_JSON=$(cat <<'TUMBLEWEED_JSON_EOF'
${jsonText}
TUMBLEWEED_JSON_EOF
)

# 选择 JSON 解析器：jq 优先，python3 兜底
if command -v jq >/dev/null 2>&1; then
  jq_iter() { jq -r "$1" <<<"$TUMBLEWEED_JSON"; }
  jq_each_file() {
    echo "$TUMBLEWEED_JSON" | jq -c '.files[]' | while IFS= read -r line; do
      jq -r "$1" <<<"$line"
    done
  }
elif command -v python3 >/dev/null 2>&1; then
  jq_iter() { python3 -c "import json,sys; d=json.load(sys.stdin); print($1)" <<<"$TUMBLEWEED_JSON"; }
  jq_each_file() {
    python3 -c "
import json, sys
d = json.load(sys.stdin)
for f in d['files']:
    print(f)
" <<<"$TUMBLEWEED_JSON" | while IFS= read -r line; do
      python3 -c "import json,sys; f=json.load(sys.stdin); print($1)" <<<"$line"
    done
  }
else
  echo "ERROR: 需要 jq 或 python3 来解析 Tumbleweed.json" >&2
  exit 1
fi

sha512sum_cmd() {
  if command -v sha512sum >/dev/null 2>&1; then
    sha512sum "$1" | awk '{print $1}'
  elif command -v shasum >/dev/null 2>&1; then
    shasum -a 512 "$1" | awk '{print $1}'
  else
    python3 -c "import hashlib,sys; print(hashlib.sha512(open(sys.argv[1],'rb').read()).hexdigest())" "$1"
  fi
}

mkdir -p mods config defaultconfigs kubejs plugins libraries scripts resourcepacks shaderpacks

# 1. 还原 overrides
echo "[1/6] 还原 overrides……"
if [ -d overrides ]; then
  if command -v unzip >/dev/null 2>&1; then
    unzip -oq overrides.zip 2>/dev/null || true
  fi
  cp -rf overrides/* . 2>/dev/null || true
fi

# 2. 下载 files
echo "[2/6] 下载 mods / plugins……"
CORE_TYPE=$(jq_iter '.server.core.type')
LOADED=0
EMBEDDED=0

jq_each_file ".path" | while IFS= read -r PATH_REL; do
  echo "path=$PATH_REL"
done

python3 - <<'PYEOF' 2>&1 || true
import json, os, sys, hashlib, urllib.request
import shutil
from concurrent.futures import ThreadPoolExecutor, as_completed

json_text = """${jsonText}"""
d = json.loads(json_text)

def sha512(p):
    h = hashlib.sha512()
    with open(p, 'rb') as f:
        while True:
            b = f.read(1<<20)
            if not b: break
            h.update(b)
    return h.hexdigest()

TOTAL = len(d.get('files', []))
done = [0]
max_workers = max(4, min(16, (TOTAL or 1)))
print(f"  共 {TOTAL} 个文件，并发 {max_workers} 下载")

def handle(f):
    path = f['path']
    dl = f.get('downloads', [])
    expected = f['hashes']['sha512']
    os.makedirs(os.path.dirname(path) or '.', exist_ok=True)
    if dl:
        url = dl[0]
        try:
            req = urllib.request.Request(url, headers={'User-Agent':'tumbleweed-deploy/0.1'})
            with urllib.request.urlopen(req, timeout=180) as r, open(path, 'wb') as out:
                while True:
                    b = r.read(1<<20)
                    if not b: break
                    out.write(b)
        except Exception as e:
            return (path, f"下载失败: {e}")
        if expected and sha512(path).lower() != expected.lower():
            return (path, "sha512 校验失败")
    else:
        embed = f.get('embedPath') or ('overrides/' + path)
        try:
            shutil.copyfile(embed, path)
        except Exception as e:
            return (path, f"复制失败: {e}")
        if expected and sha512(path).lower() != expected.lower():
            return (path, "sha512 校验失败")
    done[0] += 1
    return (path, None)

errors = []
with ThreadPoolExecutor(max_workers=max_workers) as pool:
    futures = {pool.submit(handle, f): f for f in d.get('files', [])}
    for fut in as_completed(futures):
        path, err = fut.result()
        if err:
            print(f"  ERROR {path}: {err}", file=sys.stderr)
            errors.append(path)
        else:
            print(f"  [{done[0]}/{TOTAL}] OK {path}")

sys.exit(0 if not errors else 1)
PYEOF

# 3. 下载 loader / server core
echo "[3/6] 下载 server core ($CORE_TYPE)……"
CORE_URL=$(jq_iter '.server.core.installerUrl')
CORE_FILE=$(jq_iter '.server.core.installerFileName')
CORE_MODE=$(jq_iter '.server.core.launchMode')
if command -v curl >/dev/null 2>&1; then
  curl -fsSL -o "$CORE_FILE" "$CORE_URL"
else
  python3 -c "import urllib.request; urllib.request.urlretrieve('$CORE_URL', '$CORE_FILE')"
fi

case "$CORE_MODE" in
  installer)
    echo "[4/6] 运行 installer 安装 libraries……"
    if [ "$CORE_TYPE" = "fabric" ]; then
      MC=$(jq_iter '.server.core.mcVersion')
      LD=$(jq_iter '.server.core.loaderVersion')
      INSTALL_CMD="java -jar \"$CORE_FILE\" server -mcversion \"$MC\" -loader \"$LD\" -downloadMinecraft"
      if [ -n "\${JAVA_HOME:-}" ]; then
        INSTALL_CMD="\${JAVA_HOME}/bin/java -jar \"$CORE_FILE\" server -mcversion \"$MC\" -loader \"$LD\" -downloadMinecraft"
      fi
    else
      if [ -n "\${JAVA_HOME:-}" ]; then
        INSTALL_CMD="\${JAVA_HOME}/bin/java -jar \"$CORE_FILE\" --installServer"
      else
        INSTALL_CMD="java -jar \"$CORE_FILE\" --installServer"
      fi
    fi
    # 最多重试 5 次：已下载的 libraries 会被跳过，只重试失败的
    for ATTEMPT in 1 2 3 4 5; do
      echo "  installer 第 $ATTEMPT/5 次尝试……"
      if eval "$INSTALL_CMD"; then
        echo "  installer 成功"
        break
      fi
      if [ "$ATTEMPT" -eq 5 ]; then
        echo "  installer 5 次均失败，请检查网络（maven.neoforged.net 可能被墙）" >&2
        exit 1
      fi
      echo "  installer 失败，等待 3 秒后重试……" >&2
      sleep 3
    done
    rm -f "$CORE_FILE"
    ;;
  paperclip|vanilla|launch-jar)
    echo "[4/6] 直接使用 $CORE_FILE 作为 server.jar"
    if [ -f "$CORE_FILE" ]; then mv -f "$CORE_FILE" server.jar; fi
    ;;
esac

# 5. eula.txt
echo "eula=true" > eula.txt
echo "[5/6] 已写入 eula.txt"

# 6. 全量校验
echo "[6/6] 最终校验……"
python3 - <<'PYEOF'
import json, os, sys, hashlib
from concurrent.futures import ThreadPoolExecutor, as_completed

d = json.loads("""${jsonText}""")

def sha512(p):
    h = hashlib.sha512()
    with open(p, 'rb') as f:
        while True:
            b = f.read(1<<20)
            if not b: break
            h.update(b)
    return h.hexdigest()

def check_one(f):
    p = f['path']
    if not os.path.exists(p):
        return (p, "MISSING")
    if f['hashes'].get('sha512') and sha512(p).lower() != f['hashes']['sha512'].lower():
        return (p, "HASH MISMATCH")
    return (p, None)

bad = []
files = d.get('files', [])
max_workers = max(4, min(16, (len(files) or 1)))
with ThreadPoolExecutor(max_workers=max_workers) as pool:
    for fut in as_completed([pool.submit(check_one, f) for f in files]):
        p, err = fut.result()
        if err:
            print(f"  {err}: {p}", file=sys.stderr)
            bad.append(p)

for ef in d.get('server', {}).get('extraFiles', []):
    p = ef['path']
    if ef.get('packed') and not os.path.exists(p):
        print(f"  EXTRA MISSING: {p}", file=sys.stderr)
        bad.append(p)

sys.exit(0 if not bad else 1)
PYEOF

if [ $? -eq 0 ]; then
  if [ -f run.sh ]; then
    echo "✓ Tumbleweed 部署完成。NeoForge 21+ 请运行：bash run.sh"
  elif [ -f fabric-server-launch.jar ]; then
    echo "✓ Tumbleweed 部署完成。运行：java -jar fabric-server-launch.jar nogui"
  elif [ -f server.jar ]; then
    echo "✓ Tumbleweed 部署完成。运行：java -jar server.jar nogui"
  fi
else
  echo "✗ 校验失败，请排查上方错误"
  exit 1
fi
`;
}

/**
 * PowerShell 主实现；bat 仅作为 thin launcher 调用它。
 */
function renderPowerShell(json: TumbleweedJson): string {
  const jsonText = JSON.stringify(json, null, 2);
  return `# Tumbleweed deploy.ps1 — generated by tumbleweed-mc ${json.tumbleweed?.packerVersion ?? '0.1.0'}
# 用法：powershell -ExecutionPolicy Bypass -File deploy.ps1 [-WorkDir <path>]
[CmdletBinding()]
param(
  [string]$WorkDir = "."
)

$ErrorActionPreference = "Stop"
Set-Location $WorkDir
Write-Host "Generated by Tumbleweed ${json.tumbleweed?.packerVersion ?? '0.1.0'}"

# 内嵌 Tumbleweed.json
$JsonText = @'
${jsonText}
'@

$Config = $JsonText | ConvertFrom-Json

function Download-With-Retry {
  param([string]$Url, [string]$OutPath, [int]$Retries = 3)
  for ($i = 1; $i -le $Retries; $i++) {
    try {
      Write-Host "  下载 $OutPath <- $Url"
      $tmp = "$OutPath.part"
      Invoke-WebRequest -Uri $Url -OutFile $tmp -UseBasicParsing -UserAgent 'tumbleweed-deploy/0.1'
      Move-Item -Force $tmp $OutPath
      return
    } catch {
      if ($i -eq $Retries) { throw }
      Start-Sleep -Seconds (2 * $i)
    }
  }
}

# 创建目录
$dirNames = @('mods','config','defaultconfigs','kubejs','plugins','libraries','scripts','resourcepacks','shaderpacks')
foreach ($d in $dirNames) { New-Item -ItemType Directory -Force -Path $d | Out-Null }

# 1. 还原 overrides
Write-Host "[1/6] 还原 overrides……"
if (Test-Path overrides) {
  Copy-Item -Recurse -Force overrides/* . 2>$null
}

# 2. 下载 / 还原 files（用 curl.exe，原生支持 Unicode 路径）
Write-Host "[2/6] 下载 mods / plugins……"
$total = $Config.files.Count
Write-Host "  共 $total 个文件"

# 准备所有目录
$dirsToCreate = $Config.files | ForEach-Object { Split-Path $_.path -Parent } | Where-Object { $_ } | Sort-Object -Unique
foreach ($d in $dirsToCreate) { New-Item -ItemType Directory -Force -Path $d | Out-Null }

function Get-FileSha512($p) {
  $s = $null; $sha = $null
  try {
    $s = [System.IO.File]::OpenRead($p)
    $sha = [System.Security.Cryptography.SHA512]::Create()
    return ([System.BitConverter]::ToString($sha.ComputeHash($s)) -replace '-', '').ToLower()
  } finally {
    if ($sha) { $sha.Dispose() }
    if ($s) { $s.Dispose() }
  }
}

$downloadErrors = [System.Collections.Generic.List[string]]::new()
$done = 0

foreach ($f in $Config.files) {
  $done++
  $path = $f.path
  $dir = Split-Path $path -Parent
  if ($dir) { New-Item -ItemType Directory -Force -Path $dir | Out-Null }

  if ($f.downloads -and $f.downloads.Count -gt 0) {
    $url = $f.downloads[0]
    $tmp = "$path.part"
    if (Test-Path -LiteralPath $tmp) { Remove-Item -LiteralPath $tmp -Force }
    # curl.exe -o 路径走字面量，[-] 不会被当通配符
    $curlOk = $false
    for ($i = 1; $i -le 3; $i++) {
      & curl.exe -fsSL --retry 3 --retry-delay 2 --connect-timeout 30 -o $tmp -H "User-Agent: tumbleweed-deploy/0.1" $url 2>$null
      if ($LASTEXITCODE -eq 0 -and (Test-Path -LiteralPath $tmp)) {
        $curlOk = $true
        break
      }
      if ($i -lt 3) { Start-Sleep -Seconds (2 * $i) }
    }
    if (-not $curlOk) {
      $downloadErrors.Add($path) | Out-Null
      Write-Host ("  [{0}/{1}] FAIL {2}: curl 下载失败" -f $done, $total, $path)
      continue
    }
    if (Test-Path -LiteralPath $path) { Remove-Item -LiteralPath $path -Force }
    Rename-Item -LiteralPath $tmp -NewName (Split-Path $path -Leaf)
  } else {
    $embed = if ($f.embedPath) { $f.embedPath } else { "overrides/$path" }
    try {
      Copy-Item -LiteralPath $embed -Destination $path -Force
    } catch {
      $downloadErrors.Add($path) | Out-Null
      Write-Host ("  [{0}/{1}] FAIL {2}: 复制失败" -f $done, $total, $path)
      continue
    }
  }

  if (-not (Test-Path -LiteralPath $path)) {
    $downloadErrors.Add($path) | Out-Null
    Write-Host ("  [{0}/{1}] FAIL {2}: 文件不存在" -f $done, $total, $path)
    continue
  }

  if ($f.hashes.sha512) {
    $actual = Get-FileSha512 $path
    if ($actual -ne $f.hashes.sha512.ToLower()) {
      $downloadErrors.Add($path) | Out-Null
      Write-Host ("  [{0}/{1}] FAIL {2}: sha512 不匹配" -f $done, $total, $path)
      continue
    }
  }
  Write-Host ("  [{0}/{1}] OK   {2}" -f $done, $total, $path)
}

if ($downloadErrors.Count -gt 0) {
  throw "下载失败 $($downloadErrors.Count) 个：$($downloadErrors -join ', ')"
}

# 3. 下载 server core
Write-Host "[3/6] 下载 server core ($($Config.server.core.type))……"
$core = $Config.server.core
$coreUrl = $core.installerUrl
$coreFile = $core.installerFileName
Download-With-Retry -Url $coreUrl -OutPath $coreFile

# 4. 安装 / 准备 server.jar
Write-Host "[4/6] 安装 loader……"
switch ($core.launchMode) {
  'installer' {
    $java = if ($env:JAVA_HOME) { "$env:JAVA_HOME/bin/java.exe" } else { 'java' }
    # 最多重试 5 次：已下载的 libraries 会被跳过，只重试失败的
    $installOk = $false
    for ($attempt = 1; $attempt -le 5; $attempt++) {
      Write-Host "  installer 第 $attempt/5 次尝试……"
      try {
        if ($core.type -eq 'fabric') {
          & $java -jar $coreFile server -mcversion $core.mcVersion -loader $core.loaderVersion -downloadMinecraft
        } else {
          & $java -jar $coreFile --installServer
        }
        if ($LASTEXITCODE -eq 0 -or $null -eq $LASTEXITCODE) {
          Write-Host "  installer 成功"
          $installOk = $true
          break
        }
      } catch { }
      if ($attempt -lt 5) {
        Write-Host "  installer 失败，等待 3 秒后重试……" -ForegroundColor Yellow
        Start-Sleep -Seconds 3
      } else {
        Write-Host "  installer 5 次均失败，请检查网络（maven.neoforged.net 可能被墙）" -ForegroundColor Red
        throw "installer 安装失败"
      }
    }
    Remove-Item -Force $coreFile
  }
  'paperclip' { Move-Item -Force $coreFile server.jar }
  'vanilla'   { Move-Item -Force $coreFile server.jar }
  'launch-jar'{ Move-Item -Force $coreFile server.jar }
}

# 5. eula.txt
Set-Content -Path eula.txt -Value "eula=true" -Encoding ascii
Write-Host "[5/6] 已写入 eula.txt"

# 6. 全量校验（串行，用 LiteralPath 避免 [-] 通配符问题）
Write-Host "[6/6] 最终校验……"
$bad = [System.Collections.Generic.List[string]]::new()
$total = $Config.files.Count
$verifyDone = 0
foreach ($f in $Config.files) {
  $verifyDone++
  if (-not (Test-Path -LiteralPath $f.path)) {
    Write-Error "MISSING: $($f.path)"
    $bad.Add($f.path) | Out-Null
    continue
  }
  if ($f.hashes.sha512) {
    $expected = $f.hashes.sha512.ToLower()
    $actual = Get-FileSha512 $f.path
    if ($actual -ne $expected) {
      Write-Error "HASH MISMATCH: $($f.path)"
      $bad.Add($f.path) | Out-Null
    }
  }
}
foreach ($ef in $Config.server.extraFiles) {
  if ($ef.packed -and -not (Test-Path -LiteralPath $ef.path)) {
    Write-Error "EXTRA MISSING: $($ef.path)"
    $bad.Add($ef.path) | Out-Null
  }
}

if ($bad.Count -eq 0) {
  if (Test-Path run.bat) {
    Write-Host "OK Tumbleweed 部署完成。NeoForge 21+ 请运行：.\run.bat"
  } elseif (Test-Path fabric-server-launch.jar) {
    Write-Host "OK Tumbleweed 部署完成。运行：java -jar fabric-server-launch.jar nogui"
  } elseif (Test-Path server.jar) {
    Write-Host "OK Tumbleweed 部署完成。运行：java -jar server.jar nogui"
  }
} else {
  throw "校验失败：$($bad.Count) 个文件缺失或哈希不匹配：$($bad -join ', ')"
}
`;
}

function renderBatch(json: TumbleweedJson): string {
  const ver = json.tumbleweed?.packerVersion ?? '0.1.0';
  return `@echo off
REM Tumbleweed thin launcher - generated by tumbleweed-mc ${ver}
setlocal enableextensions

echo Generated by Tumbleweed ${ver}

where pwsh >nul 2>nul
if %errorlevel%==0 (
  pwsh -NoProfile -ExecutionPolicy Bypass -File "%~dp0deploy.ps1" -WorkDir "%~dp0." %*
) else (
  powershell -NoProfile -ExecutionPolicy Bypass -File "%~dp0deploy.ps1" -WorkDir "%~dp0." %*
)

set "RC=%errorlevel%"
endlocal & exit /b %RC%
`;
}

export function renderDeployScripts(json: TumbleweedJson): {
  sh: string;
  ps1: string;
  bat: string;
} {
  return {
    sh: renderBash(json),
    ps1: renderPowerShell(json),
    bat: renderBatch(json),
  };
}
