import type { TumbleweedJson } from '../types.ts';

/**
 * 把 Tumbleweed.json 嵌入 bash here-doc，再附带 deploy.sh 主体逻辑。
 * 用户解压 zip 后只需 `bash deploy.sh` 即可。
 */
function renderBash(json: TumbleweedJson): string {
  const jsonText = JSON.stringify(json, null, 2);
  return `#!/usr/bin/env bash
# Tumbleweed deploy.sh — generated by tumbleweed-mc ${json.tumbleweed?.packerVersion ?? '0.1.0'}
# 用法：bash deploy.sh [工作目录]
set -euo pipefail

echo "Generated by Tumbleweed ${json.tumbleweed?.packerVersion ?? '0.1.0'}"

WORK="\${1:-.}"
cd "$WORK"

# 内嵌 Tumbleweed.json（here-doc）
TUMBLEWEED_JSON=$(cat <<'TUMBLEWEED_JSON_EOF'
${jsonText}
TUMBLEWEED_JSON_EOF
)

# 选择 JSON 解析器：jq 优先，python3 兜底
if command -v jq >/dev/null 2>&1; then
  jq_iter() { jq -r "$1" <<<"$TUMBLEWEED_JSON"; }
  jq_each_file() {
    echo "$TUMBLEWEED_JSON" | jq -c '.files[]' | while IFS= read -r line; do
      jq -r "$1" <<<"$line"
    done
  }
elif command -v python3 >/dev/null 2>&1; then
  jq_iter() { python3 -c "import json,sys; d=json.load(sys.stdin); print($1)" <<<"$TUMBLEWEED_JSON"; }
  jq_each_file() {
    python3 -c "
import json, sys
d = json.load(sys.stdin)
for f in d['files']:
    print(f)
" <<<"$TUMBLEWEED_JSON" | while IFS= read -r line; do
      python3 -c "import json,sys; f=json.load(sys.stdin); print($1)" <<<"$line"
    done
  }
else
  echo "ERROR: 需要 jq 或 python3 来解析 Tumbleweed.json" >&2
  exit 1
fi

sha512sum_cmd() {
  if command -v sha512sum >/dev/null 2>&1; then
    sha512sum "$1" | awk '{print $1}'
  elif command -v shasum >/dev/null 2>&1; then
    shasum -a 512 "$1" | awk '{print $1}'
  else
    python3 -c "import hashlib,sys; print(hashlib.sha512(open(sys.argv[1],'rb').read()).hexdigest())" "$1"
  fi
}

mkdir -p mods config defaultconfigs kubejs plugins libraries scripts resourcepacks shaderpacks

# 1. 还原 overrides
echo "[1/6] 还原 overrides……"
if [ -d overrides ]; then
  if command -v unzip >/dev/null 2>&1; then
    unzip -oq overrides.zip 2>/dev/null || true
  fi
  cp -rf overrides/* . 2>/dev/null || true
fi

# 2. 下载 files
echo "[2/6] 下载 mods / plugins……"
CORE_TYPE=$(jq_iter '.server.core.type')
LOADED=0
EMBEDDED=0

jq_each_file ".path" | while IFS= read -r PATH_REL; do
  echo "path=$PATH_REL"
done

python3 - <<'PYEOF' 2>&1 || true
import json, os, sys, hashlib, urllib.request

json_text = open('/dev/stdin').read() if False else """${jsonText}"""
d = json.loads(json_text)

def sha512(p):
    h = hashlib.sha512()
    with open(p, 'rb') as f:
        while True:
            b = f.read(1<<20)
            if not b: break
            h.update(b)
    return h.hexdigest()

ok = True
for f in d.get('files', []):
    path = f['path']
    dl = f.get('downloads', [])
    expected = f['hashes']['sha512']
    os.makedirs(os.path.dirname(path) or '.', exist_ok=True)
    if dl:
        url = dl[0]
        print(f"  下载 {path} <- {url}")
        try:
            req = urllib.request.Request(url, headers={'User-Agent':'tumbleweed-deploy/0.1'})
            with urllib.request.urlopen(req, timeout=120) as r, open(path, 'wb') as out:
                while True:
                    b = r.read(1<<20)
                    if not b: break
                    out.write(b)
        except Exception as e:
            print(f"  ERROR 下载失败 {path}: {e}", file=sys.stderr)
            ok = False
            continue
        if expected and sha512(path).lower() != expected.lower():
            print(f"  ERROR sha512 校验失败: {path}", file=sys.stderr)
            ok = False
    else:
        embed = f.get('embedPath') or ('overrides/' + path)
        print(f"  从 {embed} 复制 -> {path}")
        import shutil
        shutil.copyfile(embed, path)
        if expected and sha512(path).lower() != expected.lower():
            print(f"  ERROR sha512 校验失败: {path}", file=sys.stderr)
            ok = False

sys.exit(0 if ok else 1)
PYEOF

# 3. 下载 loader / server core
echo "[3/6] 下载 server core ($CORE_TYPE)……"
CORE_URL=$(jq_iter '.server.core.installerUrl')
CORE_FILE=$(jq_iter '.server.core.installerFileName')
CORE_MODE=$(jq_iter '.server.core.launchMode')
if command -v curl >/dev/null 2>&1; then
  curl -fsSL -o "$CORE_FILE" "$CORE_URL"
else
  python3 -c "import urllib.request; urllib.request.urlretrieve('$CORE_URL', '$CORE_FILE')"
fi

case "$CORE_MODE" in
  installer)
    echo "[4/6] 运行 installer 安装 libraries……"
    if [ -n "\${JAVA_HOME:-}" ]; then
      "\${JAVA_HOME}/bin/java" -jar "$CORE_FILE" --installServer
    else
      java -jar "$CORE_FILE" --installServer
    fi
    rm -f "$CORE_FILE"
    ;;
  paperclip|vanilla|launch-jar)
    echo "[4/6] 直接使用 $CORE_FILE 作为 server.jar"
    if [ -f "$CORE_FILE" ]; then mv -f "$CORE_FILE" server.jar; fi
    ;;
esac

# 5. eula.txt
echo "eula=true" > eula.txt
echo "[5/6] 已写入 eula.txt"

# 6. 全量校验
echo "[6/6] 最终校验……"
python3 - <<'PYEOF'
import json, os, sys, hashlib

d = json.loads("""${jsonText}""")

def sha512(p):
    h = hashlib.sha512()
    with open(p, 'rb') as f:
        while True:
            b = f.read(1<<20)
            if not b: break
            h.update(b)
    return h.hexdigest()

bad = 0
for f in d.get('files', []):
    p = f['path']
    if not os.path.exists(p):
        print(f"  MISSING: {p}", file=sys.stderr)
        bad += 1
        continue
    if f['hashes'].get('sha512') and sha512(p).lower() != f['hashes']['sha512'].lower():
        print(f"  HASH MISMATCH: {p}", file=sys.stderr)
        bad += 1
for ef in d.get('server', {}).get('extraFiles', []):
    p = ef['path']
    if ef.get('packed') and not os.path.exists(p):
        print(f"  EXTRA MISSING: {p}", file=sys.stderr)
        bad += 1

sys.exit(0 if bad == 0 else 1)
PYEOF

if [ $? -eq 0 ]; then
  echo "✓ Tumbleweed 部署完成。运行：java -jar server.jar nogui"
else
  echo "✗ 校验失败，请排查上方错误"
  exit 1
fi
`;
}

/**
 * PowerShell 主实现；bat 仅作为 thin launcher 调用它。
 */
function renderPowerShell(json: TumbleweedJson): string {
  const jsonText = JSON.stringify(json, null, 2);
  return `# Tumbleweed deploy.ps1 — generated by tumbleweed-mc ${json.tumbleweed?.packerVersion ?? '0.1.0'}
# 用法：powershell -ExecutionPolicy Bypass -File deploy.ps1 [-WorkDir <path>]
[CmdletBinding()]
param(
  [string]$WorkDir = "."
)

$ErrorActionPreference = "Stop"
Set-Location $WorkDir
Write-Host "Generated by Tumbleweed ${json.tumbleweed?.packerVersion ?? '0.1.0'}"

# 内嵌 Tumbleweed.json
$JsonText = @'
${jsonText}
'@

$Config = $JsonText | ConvertFrom-Json

function Get-FileSha512 {
  param([string]$Path)
  $s = $null
  $sha = $null
  try {
    $s = [System.IO.File]::OpenRead($Path)
    $sha = [System.Security.Cryptography.SHA512]::Create()
    return ([System.BitConverter]::ToString($sha.ComputeHash($s)) -replace '-', '').ToLower()
  } finally {
    if ($sha) { $sha.Dispose() }
    if ($s) { $s.Dispose() }
  }
}

function Download-With-Retry {
  param([string]$Url, [string]$OutPath, [int]$Retries = 3)
  for ($i = 1; $i -le $Retries; $i++) {
    try {
      Write-Host "  下载 $OutPath <- $Url"
      $tmp = "$OutPath.part"
      Invoke-WebRequest -Uri $Url -OutFile $tmp -UseBasicParsing -UserAgent 'tumbleweed-deploy/0.1'
      Move-Item -Force $tmp $OutPath
      return
    } catch {
      if ($i -eq $Retries) { throw }
      Start-Sleep -Seconds (2 * $i)
    }
  }
}

# 创建目录
$dirNames = @('mods','config','defaultconfigs','kubejs','plugins','libraries','scripts','resourcepacks','shaderpacks')
foreach ($d in $dirNames) { New-Item -ItemType Directory -Force -Path $d | Out-Null }

# 1. 还原 overrides
Write-Host "[1/6] 还原 overrides……"
if (Test-Path overrides) {
  Copy-Item -Recurse -Force overrides/* . 2>$null
}

# 2. 下载 / 还原 files
Write-Host "[2/6] 下载 mods / plugins……"
foreach ($f in $Config.files) {
  $path = $f.path
  $dir = Split-Path $path -Parent
  if ($dir) { New-Item -ItemType Directory -Force -Path $dir | Out-Null }
  if ($f.downloads -and $f.downloads.Count -gt 0) {
    Download-With-Retry -Url $f.downloads[0] -OutPath $path
  } else {
    $embed = if ($f.embedPath) { $f.embedPath } else { "overrides/$path" }
    Write-Host "  从 $embed 复制 -> $path"
    Copy-Item -Force $embed $path
  }
  if ($f.hashes.sha512 -and (Get-FileSha512 $path) -ne $f.hashes.sha512.ToLower()) {
    throw "SHA512 校验失败: $path"
  }
}

# 3. 下载 server core
Write-Host "[3/6] 下载 server core ($($Config.server.core.type))……"
$core = $Config.server.core
$coreUrl = $core.installerUrl
$coreFile = $core.installerFileName
Download-With-Retry -Url $coreUrl -OutPath $coreFile

# 4. 安装 / 准备 server.jar
Write-Host "[4/6] 安装 loader……"
switch ($core.launchMode) {
  'installer' {
    $java = if ($env:JAVA_HOME) { "$env:JAVA_HOME/bin/java.exe" } else { 'java' }
    & $java -jar $coreFile --installServer
    Remove-Item -Force $coreFile
  }
  'paperclip' { Move-Item -Force $coreFile server.jar }
  'vanilla'   { Move-Item -Force $coreFile server.jar }
  'launch-jar'{ Move-Item -Force $coreFile server.jar }
}

# 5. eula.txt
Set-Content -Path eula.txt -Value "eula=true" -Encoding ascii
Write-Host "[5/6] 已写入 eula.txt"

# 6. 全量校验
Write-Host "[6/6] 最终校验……"
$bad = 0
foreach ($f in $Config.files) {
  if (-not (Test-Path $f.path)) {
    Write-Error "MISSING: $($f.path)"
    $bad++
  } elseif ($f.hashes.sha512 -and (Get-FileSha512 $f.path) -ne $f.hashes.sha512.ToLower()) {
    Write-Error "HASH MISMATCH: $($f.path)"
    $bad++
  }
}
foreach ($ef in $Config.server.extraFiles) {
  if ($ef.packed -and -not (Test-Path $ef.path)) {
    Write-Error "EXTRA MISSING: $($ef.path)"
    $bad++
  }
}

if ($bad -eq 0) {
  Write-Host "OK Tumbleweed 部署完成。运行：java -jar server.jar nogui"
} else {
  throw "校验失败：$bad 个文件缺失或哈希不匹配"
}
`;
}

function renderBatch(json: TumbleweedJson): string {
  const ver = json.tumbleweed?.packerVersion ?? '0.1.0';
  return `@echo off
REM Tumbleweed thin launcher - generated by tumbleweed-mc ${ver}
setlocal enableextensions

echo Generated by Tumbleweed ${ver}

REM "%~dp0." 去掉路径末尾反斜杠，避免 PowerShell 把 \" 当转义
where pwsh >nul 2>nul
if %errorlevel%==0 (
  pwsh -NoProfile -ExecutionPolicy Bypass -File "%~dp0deploy.ps1" -WorkDir "%~dp0." %*
) else (
  powershell -NoProfile -ExecutionPolicy Bypass -File "%~dp0deploy.ps1" -WorkDir "%~dp0." %*
)

set "RC=%errorlevel%"
endlocal & exit /b %RC%
`;
}

export function renderDeployScripts(json: TumbleweedJson): {
  sh: string;
  ps1: string;
  bat: string;
} {
  return {
    sh: renderBash(json),
    ps1: renderPowerShell(json),
    bat: renderBatch(json),
  };
}
